jobs:
-
    job: 'Pytest'
    pool:
        vmImage: 'ubuntu-latest'
    strategy:
        matrix:
            Python27:
                python.version: '2.7'
            Python36:
                python.version: '3.6'

    steps:
    -
        task: UsePythonVersion@0
        inputs:
            versionSpec: '$(python.version)'

    -
        script: |
            set -e
            EXTRA_INSTALL="numpy"
            REQUIREMENTS_TXT=requirements.dev.txt
            curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
            . ./build-and-test-py-project.sh

        displayName: 'Pytest'

    -
        task: PublishTestResults@2
        inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: 'test/pytest.xml'

-
    job: 'PytestCoverage'
    pool:
        vmImage: 'ubuntu-latest'
    strategy:
        matrix:
            Python37:
                python.version: '3.7'

    steps:
    -
        task: UsePythonVersion@0
        inputs:
            versionSpec: '$(python.version)'

    -
        script: |
            set -e
            EXTRA_INSTALL="numpy"
            REQUIREMENTS_TXT=requirements.dev.txt
            PYTEST_FLAGS="--cov=pudb"
            curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
            . ./build-and-test-py-project.sh
            bash ../upload_coverage.sh

        env:
            COVERAGE: $(COVERAGE)

        displayName: 'Pytest'

    -
        task: PublishTestResults@2
        inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: 'test/pytest.xml'

-
    job: 'Flake8'
    pool:
        vmImage: 'ubuntu-latest'
    strategy:
        matrix:
            Python37:
                python.version: '3.7'

    steps:
    -
        task: UsePythonVersion@0
        inputs:
            versionSpec: '$(python.version)'

    -
        script: |
            set -e
            curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
            . ./prepare-and-run-flake8.sh pudb test

        displayName: 'Flake8'
